{% set name = "surfinpy" %}
{% set version = "2.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/symmy596/SurfinPy/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e03cca2d39b4eae81bcd8609b02eb983c05f09bbc168ff20fd18bdeaa1dc64c4

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - pyyaml
    - matplotlib-base
    - numpy
    - pymatgen
    - python >={{ python_min }}
    - scipy
    - seaborn

test:
  imports:
    - {{ name }}
  commands:
    - pip check
    - python -m unittest {{ name }}
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/symmy596/SurfinPy
  summary: Surface Phase Diagram Plotting Tools
  license: MIT
  license_file: license
  doc_url: https://surfinpy.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - awvwgk
